language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: nya6bCUO7sQtc/J/UgXdRIFz1e0RQKeFTuYNHVl1fySgysUgogHRap0cKHhHBgs8pjc9uapgSLu8qfdgaINeI+1UPH+zxmyMVDh7Q0NVFCs1qy5b5t0l4Zrf3zPD3VlViAPcaAlajre8fopT8ZDmJnn+O5v2LkmcqhQrxXyqLcx83IvV5HqpFCTGEyk6WxntUKulFauF41g3QjoJMLapUFV7hTxAyezoGoIwrYvRz2PGhy37OepA5S8BS7xKfSC2otTO/4uorndBobOTyNzuj9wdyg1ybn2AjnQmnF1c0+URLivUE13U/EfEL7iM5bzwHy8D9bMOYpxRt+ugZgfrDSmymVJ7r2QL8GXsbCU9GXi+KW6pdN8UEV25ZwQcytmoqZ9GrSnzIhOXEESoNbt0s0Ib+1Uy9j+AwoygSXA54UcWteAvltwAD75ND7HnGxQSUp47yGP0q0T/pxEesO7kMZ9h4d/3au3hsJwupqxkLSsLPSuXvz/r2YuNp245ETVPf2nvnDphT4ON/WgnAJ2mqnoyAtyv7S6Cz0z1bmDmipNAArynH4+HMTMS5R0tlKxVk6a8cVku+7sIrowH4C/IBecAzWqAM+7kjGFbTMJyu34KLp+CDbqgQGNLON92hISM+GSUSUj9lNngvO79Fr6a0dU/s2sgHHX3VTZpu+ZQ5yE=
  - secure: et3T7smv36SiZDhlhFXuYgw7sIeRkMp4aUnfr9MDwgLfqP1bwNKm8vkBj1diRyD2mkxgzJBCyxM2qa7FPIEO6FiaFV7RLc0oGVq6EB86vajKaiYCJrKY2MXbkZE01kKWrImNp2E8cs7mvlzebEe5owOe/yS7M1+jN6d4Tb68p2e7dLhArIYuwxkppTL0II6zIIGQZ2rAnp4S9DqWn3t9v9wpG3dqBr2iNC3uYo6no/ra5H+j0pN46H9yGmvNIAKoVed5S0+6PiZM90WAkNvVT6QA6Spkzh91yh0QRRdKiMmCxFDoKF8oRwabuVh2kZMv8a0/map6ebKRXB2COn62AeUf8/ZdVqAlS3YNoN0y1Hf+hx0sHEg8Y8w/zSicnxpLOkq5bCgbwWXnrOfTsaSQgWcLxtGQ0IlFVNABAjAzrPkOGRc71edQLVTTtngF34eW5yhaNFQU50mx52OcvLsPNcaR1zoWe7OtC4jVaLZwi7ssiX8yWV4cyUNI3yvX8D64YnYvTtL23ojjbSfyxDoho+a3TLdFYsNE1QLr5wSROkCiiea0IuG4a6McJ4729vg/OTSfEVLA6Xak70j3Zd7cUxG0hrqb02kqG+JFcuKUI6a9hV5fhjjVnOJijiaX2VWITa+DvSJig/tqkF0SSatkOFGHreaUokk+UXaV2GZ6H9Y=
